language: java
jdk:
- oraclejdk6

script: mvn -Pcoveralls test jacoco:report coveralls:jacoco

env:
  global:
  - EMUSTUDIO_USERNAME=vbmacher
  - secure: |-
      xWA1PAw2JxZfowGWlirwPqNjPF3npp2OIBDAyLFaAxDHvgn6kG2ApytV9qVB
      \ngr8H2fsQzMGcKkFi5QZm+wmzUUZu9Da8yQtaiDeARaIstg93Oo3Mc9UYMr
      j+\nfgkMHXRCHNxQZYyBCRLqWaPOjgyQR4mb5aBasZ0O+N7rxkFKK54=

after_success:
- python scripts/addServer.py
- mvn clean deploy --settings ~/.m2/mySettings.xml
