language: java
jdk:
- oraclejdk6
script: mvn -Pcoveralls test jacoco:report coveralls:jacoco

env:
  global:
  - EMUSTUDIO_USERNAME=vbmacher
  - secure: |-
      xcjSUo0AdRk5uGibuMwDg4/++LcF0ev9TZ6G+lzO09MyYhGb+o5sbAdeBdJh
      Jp655cNOU6JgXXt1lHjwNwdkwK5XmUoYdbydBgKI49lcl/iLe2HFyuIlG6wK
      zoLX5zkwFy3paduesm5JkM1I1K7fwJ0RCscCOoxeu+Z2khw6m10=

after_success:
- python scripts/addServer.py
- mvn clean deploy --settings ~/.m2/mySettings.xml
