language: java
jdk:
- oraclejdk6

script: mvn -Pcoveralls test jacoco:report coveralls:jacoco

env:
  global:
  - EMUSTUDIO_USERNAME=vbmacher
  - secure: |-
      hv3eoAUw75qT5KTS65vCNnqsBUV+p/BrQ94LG5NGWU8WTa5j46v9AYZ1e0wd
      t2RmblExlTy004gZFfGd3vbt+Z55iraIQDSSSvxuyLoxs5BlQNhHopltF7D5
      yEER4pcSTAWxtV98Lxw1202Ud7P0VsVlJ5w9GOQ2b3oLbN+Xfxk=

after_success:
- python scripts/addServer.py
- mvn clean deploy --settings ~/.m2/mySettings.xml
