language: java
jdk:
- oraclejdk6

script: mvn -Pcoveralls test jacoco:report coveralls:jacoco

env:
  global:
  - EMUSTUDIO_USERNAME=vbmacher
  - secure: |-
      t+hUfAX/Pn3YDjEhzh/MfvTkOWM0meXmc3BRidx9PtEL7iMZqH3ayqueaU2J
      qU+8X7Sb2lJJCd2c0yhFYOVV6/FHXmPOKkZ9Lg7W1QlC0Ix1nceZuK4mP6Ck
      RI4hifF836e85PtkuNOa2X3vV+gC0N+Y31wIYeTXIEbc+wqwNpM=

after_success:
- python scripts/addServer.py
- mvn clean deploy --settings ~/.m2/mySettings.xml
